name: mechanic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  connectivity_plus: ^6.1.2
  get_it: ^8.0.3
  keyboard_dismisser: ^3.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  formz: ^0.8.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  easy_localization: ^3.0.7
  mask_text_input_formatter: ^2.9.0
  pinput: ^4.0.0
  top_snackbar_flutter: ^3.1.0
  vibration: ^3.1.1
  device_info_plus: ^11.2.1
  shared_preferences: ^2.4.0
  otp_pin_field: ^1.4.0
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  audio_waveforms: ^1.3.0
  just_audio: ^0.10.4

  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.4.0
  go_router: ^16.0.0
  geolocator: ^13.0.3
  url_launcher: ^6.3.2
  flutter_swipe_button: ^2.1.3
#  mapbox_gl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.8.8
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/raw/
    - assets/translations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

